name: mentorlink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+6
  flutter_pdfview: ^1.4.0+1
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.5.0
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.4
  intl: ^0.20.2
  camera: ^0.11.1
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  video_player: ^2.9.5
  mime: ^2.0.0
  provider: ^6.1.5
  pdf: ^3.11.3
  flutter_material_color_picker: ^1.2.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  open_file_plus: ^3.4.1+1
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  syncfusion_flutter_pdfviewer: ^29.2.10
  emoji_picker_flutter: ^4.3.0
  foundation: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/school_logo.png
    - assets/images/admin_avatar.png




